### ISSUE TITLE
Добавление Файла

### ISSUE THREAD

**Issue by Duawe** [AttractorRubyJedi/attractor_crm#20]
Конечный результат:

Загружать файлы(аватар, сканер).

План решения:
1)Добавить ActiveStorage для загрузки фото
2)Добавить в модель Студента "has_one_attached :avatar" и "has_one_attached :picture "
3)Добавить в модель Преподавателя "has_one_attached :avatar"
4)Добавить в форму создания студента:
Для аватара:

<%= f.label :avatar %>
<%= f.file_field :avatar %>
Для паспортных данных:
<%= f.label :picture %>
<%= f.file_field :picture %>
5)При выводе данных в личный кабинет выводить и аватар студента и преподавателя

Мотивация:

На данный момент студент и преподаватель не может загружать файлы
Критерии приёмки:

(текст gerkin сценария)

При добавление нового преподавателя  и пользвателя сделать возможность добавить аватарку для них

Планируемое время работы:
2 час

**Comment by ali-muhammed** [comment]
выполнено
