### ISSUE TITLE
Добавить пользвательскую информацию для Student, Teacher + сканер паспорта

### ISSUE THREAD

**Issue by Duawe** [AttractorRubyJedi/attractor_crm#21]
Конечный результат:

Добавить студенту и преподавателю возможность редактировать свои данные и загружать файлы(аватар, сканер).

План решения:
1) добавить в контроллер "Student" 
- методы ( show, edit, update )
- добавить параметр "group_id"
- с "Active_storage"  добавить аватар студента 
2) добавить в контроллер "Teacher"
- методы ( show, edit, update )
- с "Active_storage"  добавить аватар преподавателя
- добавить параметр "group_id" с сылкой на  show ( group )
3) добавить в контроллер "Admin"
- сканер паспорта при создание "Student"(new) ( сделать как добавление картинки )

Мотивация:
На данный момент студент и преподаватель не может загружать файлы и админ не может добавить сканер паспорта

Критерии приёмки:

(текст gerkin сценария)

1) Если  пользователь входит как "Student", он должен видеть свои данные с аватаркой и группой
2) Если  пользователь входит как "Teacher", он должен видеть свои данные с аватаркой и группой
3) Добавить в создание студента в админке возможность сканировать паспорт

Планируемое время работы:
6 час

**Comment by ali-muhammed** [comment]
выполнено
