### ISSUE TITLE
Реализовать всё таки вход в систему через одну кнопку

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#29]
Давно планируем, но пока так и не реализовали

**Comment by izhanov** [comment]
Реализовал.
В базовых контроллерах сущностей Student, Teache, Administrator.
Подредактировал layout кабинетов пользователей

**Comment by izhanov** [comment]
Реализовал вход через одну кнопку.
Добавил в базовые контроллеры сущностей проверку пользователей- check_user()
Подредактировал layout кибинетов пользователей
