### ISSUE TITLE
Привязывание нескольких групп студенту из show студента

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#31]
Реализация данного тикета предполагает: 
1. Убрать добавление группы студенту в форме создания студента. 
2. Добавить на странице show студента: 
 2.1. Список всех групп студента.
 2.2. Кнопка добавления группы студенту(далее - кнопка добавления).
>По нажатию на кнопку добавления выводится модальное окно со списком всех групп школы. 
>Можно кликнуть одну группу и тогда user_in_groups_controller создаст одну запись в соответствующую таблицу для студента, на странице которой мы сейчас находимся. 
3. После добавлении группы студенту произойдёт редирект на страницу актуального студента.

**Comment by ali-muhammed** [comment]
сделано
