### ISSUE TITLE
Календарный план группы

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#37]
В данный момент на странице show группы должен отображаться список всех Event-ов группы. Теперь мы можем создать новую сущность - Календарный план" - это event группы и datetime. 
1. Создать таблицу calendar_plans с полями: group_id, event_id, date:datetime.
2. Под списком всех занятий группы будет кнопка "Сформировать календарный план".
3. Переходим по кнопке и видим список всех занятий, напротив каждого из которых поле для datetime.
4. Задать каждому занятию свой datetime и одним сабмитом создать столько записей в calendar_plans.

**Comment by izhanov** [comment]
Закрыт в связи с изменением реализации создания сущности Event.
