### ISSUE TITLE
Добавление групп студентам

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#41]
Необходимо завершить функционал добавления групп студентам.
1. Убрать добавление групп студентам из формы создания студента.
2. После создания нового студента сделать редирект на новоиспеченный show этого студента. 
3. Сделать на show студента кнопку для создания новой записи в таблицу user_in_groups.
4. По нажатию на кнопку должно появится модальное окно со списком всех имеющихся в школе групп. 
5. Пользователь должен выбрать одну группу и сделать submit, после чего снова произойдёт  редирект на show этого студента
6. На show студента должна появится только что добавленная группа. 
7. Эту операцию можно проделать множество раз.

**Comment by ali-muhammed** [comment]
сделано
