### ISSUE TITLE
Рефакторинг функционала создания и редактирования Event-а группы

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#42]
Проблема: у нас имеется одна кнопка для создания Event-а и одна кнопка для редактирования Event-а. По нажатию на какую-либо из кнопок, срабатывает один контроллер - events_controller, в котором нет знания, какой из Event-ов сейчас надо обработать: Lesson или Exam. Пока что мы решили это тем, что в методе event_params с помощью множественного ветвления определяем, какой из двух типов нам нужен(find_event), после чего происходит либо create, либо update. Данное решение требует рефакторинга.

**Comment by izhanov** [comment]
Закрыт в связи с потерей актуальности.
