### ISSUE TITLE
Отображение групп в котором учится студент

### ISSUE THREAD

**Issue by izhanov** [AttractorRubyJedi/attractor_crm#46]
Необходимо реализовать отображение всех групп, в которых проходит обучение, зашедший в систему студент (после прохождения логина). В данный момент при входе студента в свой кабинет отображается личная информация студента с возможностью произвести изменения.

1) Во вьюхе index profile контроллера необходимо убрать разметку отображения личной информации;
2) Добавить разметку добавляющая список групп с ссылками на их вьюху show где проходит обучение студент;
3) Переходя на вьюху show группы  студент видит все занятия в данной группы.

**Comment by ali-muhammed** [comment]
сделано
