### ISSUE TITLE
Исправления

### ISSUE THREAD

**Issue by Duawe** [AttractorRubyJedi/attractor_crm#56]
1. В контроллере студента ( который находиться в контроллере администратора )

- Заменить переменную " skype " на "telegram"

- переменная "email" должна быть не изменной  ( Админ меняет "email" )

-  ФИО не меняет, но отображает

2. Убрать студента из группы

3. Студент должнен видеть занятие при определенной даты

**Comment by Duawe** [comment]
сделал 1 пункт тикета

**Comment by izhanov** [comment]
Закрыт в связи с необходимостью переопределения 2 и 3 в отдельные тикеты. Обсуждение с заказчиком.
