### ISSUE TITLE
Задачи на итерацию №8.

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#64]
Общая задача: _максимально уплотнить цикл создания и проверки домашнего задания студентом и преподавателем соответственно_. 

Подзадачи: 
1) Сделать читабельные DateTime-ы.
В настоящее время, к примеру, дата начала занятий отображается в следующем виде: _2000-01-01 19:30:00 UTC_, что является не совсем читабельным для нашего пользователя.
2) Исправить цикл в коде, отображающий в кабинете студента во вкладке мои занятия список всех event-ов. Сейчас каждый Event представляет собой таблицу, но все Event-ы должны находится в одной таблице. 
3) В кабинете администратора при создании нового Event-а сделать время начала занятий по умолчанию 19:30, чтобы не приходилось каждый раз вводить это  самому. 
4) Сделать так, чтобы Event содержал два текстовых поля в виде WYSIWYG для раздаточного материала и домашнего задания, при этом оставить возможность прикрепления файлов в качестве доп.материалов (картинки, мокапы и т.п.).
5) Добавить в Event новое поле, которое будет выполнять функцию критерия необходимости сдавать домашку для данного Event-а. Что-то типа "Данный ивент требует домашки от студента" - да или нет (по умолчанию включенный выключатель). Если да, то добавьте дату дедлайна. 
6) В форме создания Event-а из кабинета администратора переименовать label "Месяц" для поля "shift" в "Учебный месяц".
7) Заполнение полей реальными данными, чтобы видеть на экране текст в том количестве, в котором он должен быть. Например, раздаточный материал, домашнее задание, описание и т.д.
8) Улучшить пользовательский интерфейс, чтобы пользователь однозначно понимал, где он находится и что от него требуется в данный момент. Например, переход на страницу создания домашнего задания должен ясно показывать, что пользователь сейчас находится на странице создания домашнего задания (а не просто форма создания) и что от него требуются следующие шаги: загрузить файл и т.д. 
9) После создания домашки система должна перенаправить пользователя на предыдущую страницу со списком всех Event-ов, где должно отобразиться уведомление о том, что домашка для этого Event-а уже создана, с предложением отправить домашку для этого Event-а заново. 
10) Автоматическое заполнение поля домашки title в следующем формате: homework_#_name_surname.
11) Скачивание файлов на локальную машину. 
12) Переделать дизайн страниц в соответствии с принципом "Громкого и тихого разговора системы с пользователем" (было объяснено заказчиком). Например, самые яркие кнопки должны указывать на самые актуальный действия пользователя. Сейчас самой яркой кнопкой системы является кнопка на выход. Исключить "кричащий" дизайн для текста (например, черная таблица).
13) Разработать систему версионности домашек, а также проверки и выставления оценок в соответствии с дедлайном.
14) В кабинете преподавателя, при переходе на страницу группы преподавателя, разделить тамошние блоки "Список группы" и "Список уроков и контрольных работ(event-ов)" на tabs. 
15) В блоке "Список уроков и контрольных работ(event-ов)" сделать соответствующие друг другу дату и время Event-а (сейчас значение Дата содержит 2000-й год, а Время - 2019-й).
16) Добавить в кабинете преподавателя tab для "Домашние работы студентов". В этой вкладке пользователь(преподаватель) должен видеть список всех Event-ов и при необходимости ознакомиться с данными по Event-у. Переход на какой-то Event должен показать список студентов группы. Переход по каждому студенту должен открывать страницу со списком всех домашек этого студента для этого Event-а. Таким образом, пользователь может видеть все версии домашки, отправленные студентом для текущего Event-а. Название домашки и ссылка на скачивание файла + ссылка на Edit этой домашки (в виде "Дать feedback и оценку"), то есть для заполнения полей feedback(WYSIWYG) и grade.
17) Преподаватель скачивает архив, проверяет его на локальной машине. Переходит на страницу "Дать feedback и оценку", и заполняет два предложенных поля. 
18) Таким образом, в кабинете студента, пользователь(студент), должен видеть, что его домашка проверена (критерий - feedback и grade заполнены).

**Comment by izhanov** [comment]
Закрыт в связи с тем, что половина задач выделены в отдельные тикеты.
