### ISSUE TITLE
Читабельные даты (для всех кабинетов)

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#66]
Отображение значений полей типов date, time и datetime сделать читабельными везде, где они используются
- **User** - birth_date, passport_date. 
- **Group** - data_start, data_end.
- **Event** - event_date, event_time, student_work_deadline. 
Можно использовать метод поле._strftime("%d %m %Y %H : %M")_.

**Comment by Duawe** [comment]
сделано
