### ISSUE TITLE
Поля content и home_task для Event (для всех кабинетов)

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#67]
В Event:
1) добавить новое поле home_task типа text (поле для домашнего задания по занятию); 
2) заменить за ненадобностью поле description типа text на поле content типа text (поле для учебного материала занятия). 

В AdministratorCabinet и TeacherCabinet:
- данные поля формы (при создании Event-а преподавателем или администратором) должны отображаться в виде WYSIWYG. 

В StudentCabinet:
- сделать соответствующее отображение данных полей при просмотре студентом Event-а:
1) Сгруппировать все Event-ы в одну таблицу.
2) Добавить ссылку на show Event-а, в котором отобразить вышеуказанные поля.

**Comment by ali-muhammed** [comment]
я возьму
