### ISSUE TITLE
поле need_task для Event(для всех кабинетов)

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#70]
Добавить в Event поле need_task типа boolean со значением по умолчанию true. 
Это поле служит критерием того, что для Event-а необходимо сдать домашку.

В AdministratorCabinet, в форме создания Event-а: 
- если need_task==true(а это по умолчанию) => предоставить для заполнения поле student_work_deadline. 
- при переключении need_task==true на false, оставить nil значением поля student_work_deadline. 

Аналогично для TeacherCabinet, так как преподаватель так же создаёт Event-ы, как и администратор. 

В StudentCabinet:
если need_task==true => показать ссылку на создание домашки;
если need_task==false => ничего не показывать.

**Comment by izhanov** [comment]
Поле need_task добавлено, не реализовано событие с позволением заполнять поле student_work_deadline.
Необходимо принять решение когда и кто будет реализовывать это событие.
