### ISSUE TITLE
Наполнение и структурирование информации в TeacherCabinet

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#75]
В данный момент TeacherCabinet представляет из себя страницу my_profile, содержащую личные данные преподавателя и ссылку на его группу. Переход на эту группу => отображаются список студентов и список event-ов этой группы. 
На встрече с заказчиком было решено привести к единому стили отображения информации в StudentCabinet и TeacherCabinet. Поэтому необходимо структурировать информацию в my_profile TeacherCabinet по tab-ам(используя bootstrap) следующим образом:
1) tab "Мои данные" => отображение личных данных преподавателя со ссылкой на edit.
2) tab "Мои группы" => отображение списка групп преподавателя.
3) tab "Мои студенты" => так как студенты разбиты по группам, показывать tab-ы групп, а внутри каждого tab-а - список студентов группы с некоторыми данными (например, контактными).
4) tab "Мои занятия" => так как занятия разбиты по группам, показывать tab-ы групп, а внутри каждого tab-а - список event-ов этой группы со ссылкой на создание нового event-а.
5) tab "Домашние работы студентов" => tab-ы групп преподавателя, в каждом => список event-ов группы, переход на Event =>  список студентов группы; каждый студент - это ссылка на страницу домашних работ этого студента для текущего Event-а =>  при переходе на каждого студента => список домашних работ этого студента для текущего Event-а, + "Проверить домашку"(сслыка на edit с полями feedback и grade) или "Проверено"(если эти поля уже заполнены).

**Comment by izhanov** [comment]
Взял в работу

**Comment by izhanov** [comment]
Функционал реализован.
