### ISSUE TITLE
Автозаполнение поля title StudentWork (для StudentCabinet)

### ISSUE THREAD

**Issue by AldiyarAmre** [AttractorRubyJedi/attractor_crm#77]
При создании пользователем(студентом) StudentWork, значение поля title должно автоматически сформироваться в следующем формате: homework_position_name_surname.
Для этого нужно:
1) Добавить новое поле position для "Event" type "Lesson" - порядковый номер занятия.
2) В new StudentWork сформировать поле :title "под капотом"(т.е. пользователь не должен это видеть и принимать в этом участие), вытаскивая @event.position, current_user.name и current_user.surname.

**Comment by Duawe** [comment]
я возьму

**Comment by izhanov** [comment]
Задача выполнена
